[package]
name = "tzhs-chat"
version = "0.1.0"
authors = ["Dowland Aiello <dowlandaiello@gmail.com>"]
edition = "2018"

[lib]
src = "src/lib.rs"
name = "libtz"

[dependencies]
actix-web = "3.3.2"
num-traits = "0.2"
num-derive = "0.3"
